config/routes.rb
 Rails.application.routes.draw do

  
  root 'home#home'
  get '/about' => 'home#about'

  get '/sign-up' => 'users#new'
  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy'

    resources :users, :regions, :journals

    resources :countries do
        resources :boardposts do
          resources :postcomments
        end

        resources :reviews do
          resources :comments
        end
    end
 

    
    

end

app/models/boardpost.rb
class Boardpost < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :postcomments

  validates_presence_of :title, :body, :user_id, :country_id
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates_presence_of :body, :user_id, :review_id
end

app/models/country.rb
class Country < ActiveRecord::Base
	belongs_to :region	
	has_many :journals
	has_many :reviews
	has_many :boardposts


  	def to_param
    	url_name
  	end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :country
  belongs_to :user

  validates_presence_of :title, :link, :user_id, :country_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :comments, dependent: :destroy

  enum post_type: [:restaurant, :hotel, :other]

 	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude, :address => :full_address

	after_validation :reverse_geocode

end

app/models/postcomment.rb
class Postcomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :boardpost

  validates_presence_of :body, :user_id, :boardpost_id
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :countries

	def to_param
    	url_name
  	end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :comments, dependent: :destroy

  enum post_type: [:restaurant, :hotel, :other]

  validates_presence_of :title, :body
  validates_presence_of :post_type, :country_id, :user_id, :latitude, :longitude, on: :create
  
 	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude, :address => :full_address

	after_validation :reverse_geocode


	def self.search(search)
		where("title ILIKE ? OR body ILIKE ? OR full_address ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reviews, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :journals, dependent: :destroy
	has_many :boardposts, dependent: :destroy

	validates_presence_of :fname, :lname, :email
	validates_presence_of :password, on: :create
	validates_uniqueness_of :email
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.order("name ASC")
  end

  def show
    set_country
    @user = current_user
    @journal = Journal.new
    @journals = @country.journals.order("created_at DESC")
    @boardpost = Boardpost.new
    @boardposts = @country.boardposts.order("created_at DESC")
    @review = Review.new
    if params[:search]
      @reviews = Review.search(params[:search]).order("created_at DESC")
    else
      @reviews = @country.reviews.order("created_at DESC")
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
    def set_country
      @country = Country.find_by(url_name: params[:id])
      unless @country
        redirect_to countries_path, notice: "I could not find that country."
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @country = Country.find_by(url_name: params[:id])
    @post = Post.find(params[:id])
  end

  def create
    @country = Country.find_by_url_name(params[:country_id])
    @post = @country.posts.build(post_params)
    # coordinates = Geocoder.coordinates(@post.address)
    # @post.latitude = coordinates[0]
    # @post.longitude = coordinates[1]
    if @post.save
      flash[:notice] = "Review added"
    else
      flash[:notice] = "Unable to add review"
    end
    redirect_to country_path(@country)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @country = @post.country
    @post.update(post_params)
    if @post.save
      flash[:notice] = "Thanks for editing"
      redirect_to country_path(@country)
    else
      flash[:notice] = "Unable to edit review"
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @country = @post.country
    if @post.destroy
      flash[:notice] = "Review removed"
    else
      flash[:notice] = "Unable to remove review"
    end
    redirect_to country_path(@country)
  end

  private
  def post_params
      params.require(:post).permit(:title, :body, :post_type, :latitude, :longitude, :address, :full_address, :user_id, :country_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardposts_helper.rb
module BoardpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/countries/_hotel_results.html.erb
<% @reviews.each do |p| %>
	<div class="individual_reviews">
		<% if p.post_type == "hotel" %>
			<h4><b><%= p.title %></b></h4>
			<p><%= p.body.truncate_words(15) %></p>
			<p>Address: <%= p.full_address %></p>
			<p><%= link_to "full review and comments (#{p.comments.count})", country_review_path(p.country, p) %> </p>
		<% end %>
	</div>
<% end %>
<%# if @reviews == [] %>
	<!-- <p>There are no reviews containing the term(s) <%#= params[:search] %>.</p> -->
<%# end %>
<%= form_tag(country_path, :method => "get", id: "search-form", remote: :true) do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search hotel reviews" %>
	<%= submit_tag "Search" %>
<% end %>

<button><%= link_to "Clear Search Filters", @country %></button>

app/views/countries/_other_results.html.erb
<% @reviews.each do |p| %>
	<div class="individual_reviews">
		<% if p.post_type == "other" %>
			<h4><b><%= p.title %></b></h4>
			<p><%= p.body.truncate_words(15) %></p>
			<p>Address: <%= p.full_address %></p>
			<p><%= link_to "full review and comments (#{p.comments.count})", country_review_path(p.country, p) %> </p>
		<% end %>
	</div>
<% end %>
<%# if @reviews == [] %>
	<!-- <p>There are no reviews containing the term(s) <%#= params[:search] %>.</p> -->
<%# end %>
<%= form_tag(country_path, :method => "get", id: "search-form", remote: :true) do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search other reviews" %>
	<%= submit_tag "Search" %>
<% end %>

<button><%= link_to "Clear Search Filters", @country %></button>

app/views/countries/_restaurant_results.html.erb
<% @reviews.each do |p| %>
	<div class="individual_reviews">
		<% if p.post_type == "restaurant" %>
			<h4><b><%= p.title %></b></h4>
			<p><%= p.body.truncate_words(15) %></p>
			<p>Address: <%= p.full_address %></p>
			<p><%= link_to "full review and comments (#{p.comments.count})", country_review_path(p.country, p) %> </p>
		<% end %>
	</div>
<% end %>
<%# if @reviews == [] %>
	<!-- <p>There are no reviews containing the term(s) <%#= params[:search] %>.</p> -->
<%# end %>
<%= form_tag(country_path, :method => "get", id: "search-form", remote: :true) do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search restaurant reviews" %>
	<%= submit_tag "Search" %>
<% end %>

<button><%= link_to "Clear Search Filters", @country %></button>

app/views/countries/index.html.erb
<div class="show_wrapper">
	<h1>All Countries</h1>
		<% @countries.each do |c| %>
			<div class="individual_countries">
				<a href="<%= country_path(c) %>"><img src="/images/<%= c.url_name %>.jpg">
				<h1 id="individual_country_name"><%= c.name %></h1>
				 </a>
				<br>
			</div>
		<% end %>
</div>

app/views/countries/show.html.erb
<div class="wrapper">
	<!-- This is the country map -->
	<div id="map"></div>

	<!-- ALL REVIEWS -->
	<div id="review_wrapper">
		<div>
			<p class="left tab one" onclick="openRestaurantModal()">Eat</p>
			<p class="left tab two" onclick="openHotelModal()">Sleep</p>
			<p class="left tab three" onclick="openOtherModal()">Play</p>
			<button class="right" id="add" onclick="openReviewModal()">Add Review</button>	
		</div>

		<!--  Create a new review -->
		<div id="outer_review_modal" class="clear">
			<div id="inner_review_modal">
				<h3>Add a Review</h3>
					<h4 id="close_review_modal" class="right" onclick="closeReviewModal()"><a href="">X</a><h4>
					<form id="search" class="clear">
						<p>Click on the map to set a location OR</p>
						<br>
						<input id="address" type="textbox" placeholder="Search by address">
				 		<input id="submit" type="submit" value="Search">
				 	</form>
					<br>
					<%= form_for [@country, @review] do |f| %>
						<%= f.text_field :title, placeholder: :name %>
						<br><br>
						<%= f.text_area :body, placeholder: :description %>
						<br>
						<%= f.hidden_field :latitude %>
						<%= f.hidden_field :longitude %>
						<%= f.hidden_field :address %>
						<br>
						<%= f.select :post_type, Review.post_types.keys, prompt: :select %>
						<br><br>
						<%= f.submit %>
					<% end %>
			</div>
		</div>

		<!-- Restaurant reviews -->
		<div id="restaurant_reviews" class="clear">
			<%= render partial: "restaurant_results" %>
		</div>

		<!-- Hotel reviews -->
		<div id="hotel_reviews" class="clear">
			<%= render partial: "hotel_results" %>
		</div>

		<!-- Other reviews -->
		<div id="other_reviews" class="clear">
			<%= render partial: "other_results" %>
		</div>
	</div>

	<!-- JOURNALS -->
	<div id="volunteer_journals">
		<h3>Volunteer Journals</h3>
		<div id="all_journals">
			<% if @journals != [] %>
				<% @journals.each do |j| %>
					<div id="individual_journals">
						<p><%= link_to j.title, j.link %></p>
						<p><%= j.description %></p>
						<p>Author: <%= link_to j.user.fname + " " + j.user.lname, user_path(j.user) %></p>
					</div>
				<% end %>
			<% else %>
				<p>None yet...</p>
			<% end %>
		</div>
	</div>

	<!-- MESSAGE BOARD -->
	<div id="message_board">
		<h3>Message Board</h3>
			<button id="post" onclick="openBoardpostModal()">POST</button>
			<div id="all_boardposts">
				<% @boardposts.each do |b| %>
					<div id="individual_boardposts">
						<p><b><%= b.title %></b></p>
						<p><%= b.body %></p>
						<p><%= link_to "full thread and comments", country_boardpost_path(b.country, b) %> </p>
					</div>
				<% end %>
			</div>
	</div>

	<!-- New message board post modal -->
	<div id="outer_boardpost_modal">
		<div id="inner_boardpost_modal">
			<p id="close_boardpost_modal" class="right" onclick="closeBoardpostModal()">X</p>
				<h2 class="clear">Post on the Message Board</h2>
				<%= form_for [@country, @boardpost] do |j| %>
					<%= j.text_field :title, placeholder: :post_title %>
					<br>
					<%= j.text_area :body, placeholder: "What's on your mind?" %>
					<br>
					<%= j.submit value: "POST", id: :submit_new_boardpost %>
				<% end %>
		</div>
	</div>

	<!-- Hidden review data to populate map with markers -->
	<% @reviews.each do |r| %>
		<div class="load_all_markers" data-thang='{"lat": <%= r.latitude %>, "lng": <%= r.longitude %>}' data-title='<%= r.title %>' data-body='<%= r.body.truncate_words(15) %>' data-details='<%= link_to "see details", country_review_path(r.country, r) %>'>
		</div>
	<% end %>

	<!-- Javascript to create country map -->
	<script type="text/javascript">
		function initialize() {

			var prev_infowindow = false;

		  var myCenter = new google.maps.LatLng(<%= @country.latitude %>, <%= @country.longitude %>)
		  var mapProp = {
		    scrollwheel: false,
		    mapTypeControl: false,
		    streetViewControl: true,
		    center:myCenter,
		    zoom:7,
		    mapTypeId:google.maps.MapTypeId.ROADMAP
		  };
		  var map=new google.maps.Map(document.getElementById("map"),mapProp);

		  // This is a marker
		  var marker = new google.maps.Marker({
		    // position:myCenter,
		  });

		  // This is a new map with a geocoded address
		  var geocoder = new google.maps.Geocoder();

		  // This function geocodes the address entered on submit in report modal
		  document.getElementById('search').addEventListener('submit', function(e) {
		    e.preventDefault();
		    var address = document.getElementById("address").value;
		    geocodeAddress(geocoder, map, address);
		  });

		  //grabs all of the things with the class load_all_markers
		  var things = document.getElementsByClassName('load_all_markers');

		  // gets the length of load_all_markers
		  var length = document.getElementsByClassName('load_all_markers').length;

		    
		  arr = [];
		  var arrTitle = [];
		  var arrBody = [];
		  var arrDetails = [];
		  // iterates through var things (array) and adds stuff to empty arrays (dataset.thang refers to html attributte data-thang)
		  for (var i = 0; i < length; i++){
		    arr.push(things[i].dataset.thang);
		    arrTitle.push(things[i].dataset.title);
		    arrBody.push(things[i].dataset.body);
		    arrDetails.push(things[i].dataset.details);
		  }

		  // var arr is now an array of objects in string form

		  // iteration of arr and returning it's object form using JSON.parse saved as variable "thung"
		  for (var j = 0; j < length; j++){

		    var thung = JSON.parse(arr[j]);
		    var rTitle = arrTitle[j];
		    var rBody = arrBody[j];
		    var rDetails = arrDetails[j];


		    // make new marker with the object thung which contains latitude and longitude
		    var marks = new google.maps.Marker({
		      position: thung,
		      map: map
		    });

		    // anchors infowindow to corresponding / specific marker
		    function addInfoWindow(marker, title, body, details) {
		     	var infoWindow = new google.maps.InfoWindow({
		          content: "<div id='info_title'>" + title + "</div>" + "<br><div id='info_body'>" + body + "<br><br></div>" + details
		        });
		     
		        // Zooms in on marker click
		        google.maps.event.addListener(marker, 'click', function () {
		        	if (prev_infowindow){
		        		prev_infowindow.close();
		        	}
				    prev_infowindow = infoWindow
		            infoWindow.open(map, this);
		            map.setZoom(16);
		            map.setCenter(marker.getPosition());
		        });
		    }
		    // Puts report title + body + details link in infowindow
		    addInfoWindow(marks,rTitle,rBody,rDetails) 
		  }
		  // Adds marker wherever you click
		  google.maps.event.addListener(map, 'click', function(event) {
				marker.setDraggable(true);
				marker.setPosition(event.latLng);
				marker.setMap(map);
				marker.setAnimation(google.maps.Animation.DROP);
				populateInputs(event.latLng);
	

		 	google.maps.event.addListener(marker, "drag", function (mEvent) {
                populateInputs(mEvent.latLng);
            });
		  });

		}
		initialize();

		// Creating reviews in the new review modal
		function openReviewModal() {
			<% if current_user == nil %>
				alert("You must be logged in to write a review")
			<% elsif @user.volunteer == false %>
				alert("Only Peace Corps Volunteers can write reviews. You can still post on the message board and make comments, though!")
			<% else %>
			  $('.tab.one').css({"border-top":"none", "border-right":"none", "border-left":"none", "border-bottom":"solid 2px #f1f1f1"});
			  $('.tab.two').css({"border-top":"none", "border-right":"none", "border-left":"none", "border-bottom":"solid 2px #f1f1f1"});
			  $('.tab.three').css({"border-top":"none", "border-right":"none", "border-left":"none", "border-bottom":"solid 2px #f1f1f1"});
			  $('#restaurant_reviews').hide();
			  $('#hotel_reviews').hide();
			  $('#other_reviews').hide();
			  $('#outer_review_modal').show();
			<% end %>
		}

		// Creating new message board posts
		function openBoardpostModal() {
			<% if current_user %>
			    $('#outer_boardpost_modal').fadeIn(200);
			<% else %>
			 	alert("You must be logged in to write a post")
			<% end %>
		}
	</script>
</div>

app/views/countries/show.js.erb
$("#restaurant_reviews").html("<%= j render(partial: 'restaurant_results') %>");
$("#hotel_reviews").html("<%= j render(partial: 'hotel_results') %>");
$("#other_reviews").html("<%= j render(partial: 'other_results') %>");