config/routes.rb
 Rails.application.routes.draw do

  
  root 'home#home'
  get '/about' => 'home#about'

  get '/sign-up' => 'users#new'
  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy'

    resources :users, :regions, :journals

    resources :countries do
        resources :boardposts do
          resources :postcomments
        end

        resources :reviews do
          resources :comments
        end
    end
 

    
    

end

app/models/boardpost.rb
class Boardpost < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :postcomments

  validates_presence_of :title, :body, :user_id, :country_id
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates_presence_of :body, :user_id, :review_id
end

app/models/country.rb
class Country < ActiveRecord::Base
	belongs_to :region	
	has_many :journals
	has_many :reviews
	has_many :boardposts


  	def to_param
    	url_name
  	end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :country
  belongs_to :user

  validates_presence_of :title, :link, :user_id, :country_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :comments, dependent: :destroy

  enum post_type: [:restaurant, :hotel, :other]

 	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude, :address => :full_address

	after_validation :reverse_geocode

end

app/models/postcomment.rb
class Postcomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :boardpost

  validates_presence_of :body, :user_id, :boardpost_id
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :countries

	def to_param
    	url_name
  	end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :comments, dependent: :destroy

  enum post_type: [:restaurant, :hotel, :other]

  validates_presence_of :title, :body
  validates_presence_of :post_type, :country_id, :user_id, :latitude, :longitude, on: :create
  
 	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude, :address => :full_address

	after_validation :reverse_geocode


	def self.search(search)
		where("title ILIKE ? OR body ILIKE ? OR full_address ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reviews, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :journals, dependent: :destroy
	has_many :boardposts, dependent: :destroy

	validates_presence_of :fname, :lname, :email
	validates_presence_of :password, on: :create
	validates_uniqueness_of :email
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end

  def show
    @review = Review.find(params[:id])
    @country = @review.country
    @user = @review.user
    @comment = Comment.new
    @comments = @review.comments.order("created_at DESC")
  end

  def create
    @country = Country.find_by_url_name(params[:country_id])
    @review = @country.reviews.build(review_params)
    @review.user_id = current_user.id
    puts @review.user_id
    if @review.save
      flash[:notice] = "Review added"
    else
      flash[:notice] = "#{@review.errors.full_messages.first}"
    end
    redirect_to country_path(@country)
  end

  def edit
    @review = Review.find(params[:id])
    @user = @review.user
    @country = @review.country
  end

  def update
    @review = Review.find(params[:id])
    @country = @review.country
    @review.update(review_params)
    if @review.save
      flash[:notice] = "Thanks for editing"
      redirect_to country_review_path(@country, @review)
    else
      flash[:notice] = "Unable to edit review"
      render "edit"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @country = @review.country
    if @review.destroy
      flash[:notice] = "Review removed"
    else
      flash[:notice] = "Unable to remove review"
    end
    redirect_to country_path(@country)
  end

  private
  def review_params
      params.require(:review).permit(:title, :body, :post_type, :latitude, :longitude, :address, :full_address, :user_id, :country_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardposts_helper.rb
module BoardpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/edit.html.erb
<h1>Edit review</h1>
	<% if current_user && @user == current_user %>
		<%= form_for [@country, @review] do |f| %>
			<%= f.text_field :title, placeholder: :name %>
			<br><br>
			<%= f.text_area :body, placeholder: :description %>
			<br>
			<%= f.hidden_field :latitude %>
			<%= f.hidden_field :longitude %>
			<br>
			<%= f.select :post_type, Review.post_types.keys, prompt: :select %>
			<br><br>
			<%= f.submit :update %>
		<% end %>
	<% else %>
		<p>You do not have permission to edit this review</p>
	<% end %>

app/views/reviews/index.html.erb
<h1>reviews#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/reviews/show.html.erb
<!-- Review detail -->
<div class="show_wrapper">
	<img class="icon" src="/images/<%= @review.post_type %>.png">
		<h1><%= @review.title %></h1>
			<h3><%= @review.body %></h3>
				<p>Posted on <%= @review.created_at.strftime("%b %d, %Y") %> by <%= @user.fname %> <%= @user.lname %></p>
						<% if current_user && @user == current_user %>
							<p class="inline"><%= link_to "Edit Review", edit_country_review_path(@country, @review) %></p>
							<p class="inline">&#9733; &nbsp;<%= link_to "Delete Review", country_review_path(@country, @review), method: :delete %></p>
						<% end %>
						<hr>

	<!-- Add a new comment -->
	<%= form_for [@review.country, @review, @comment] do |c| %>
		<%= c.text_field :body, placeholder: :what_do_you_think? %>
		<%= c.submit value: "Comment" %>
	<% end %>

	<!-- All comments -->
	<h3>Comments</h3>
		<% @comments.each do |c| %>
		<div class="individual_comments">
			<p class="inline"><%= link_to c.user.fname + " " + c.user.lname, user_path(c.user) %> says...</p>
				<% if current_user && c.user == current_user %>
					<%= link_to "Delete Comment", country_review_comment_path(@country, @review, c), method: :delete, class: :right, id: :delete_comment%>
				<% end %>
				<p class="clear"><%= c.body %></p>
				<p class="time_posted"><%= time_ago_in_words(c.created_at) %> ago</p>
			</div>
		<% end %>
</div>