config/routes.rb
 Rails.application.routes.draw do

  
  root 'home#home'
  get '/about' => 'home#about'

  get '/sign-up' => 'users#new'
  get '/log-in' => 'sessions#new'
  post '/log-in' => 'sessions#create'
  get '/log-out' => 'sessions#destroy'

    resources :users, :regions, :journals

    resources :countries do
        resources :boardposts do
          resources :postcomments
        end

        resources :reviews do
          resources :comments
        end
    end
 

    
    

end

app/models/boardpost.rb
class Boardpost < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :postcomments

  validates_presence_of :title, :body, :user_id, :country_id
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates_presence_of :body, :user_id, :review_id
end

app/models/country.rb
class Country < ActiveRecord::Base
	belongs_to :region	
	has_many :journals
	has_many :reviews
	has_many :boardposts


  	def to_param
    	url_name
  	end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :country
  belongs_to :user

  validates_presence_of :title, :link, :user_id, :country_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :comments, dependent: :destroy

  enum post_type: [:restaurant, :hotel, :other]

 	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude, :address => :full_address

	after_validation :reverse_geocode

end

app/models/postcomment.rb
class Postcomment < ActiveRecord::Base
  belongs_to :user
  belongs_to :boardpost

  validates_presence_of :body, :user_id, :boardpost_id
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :countries

	def to_param
    	url_name
  	end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  has_many :comments, dependent: :destroy

  enum post_type: [:restaurant, :hotel, :other]

  validates_presence_of :title, :body
  validates_presence_of :post_type, :country_id, :user_id, :latitude, :longitude, on: :create
  
 	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude, :address => :full_address

	after_validation :reverse_geocode


	def self.search(search)
		where("title ILIKE ? OR body ILIKE ? OR full_address ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :reviews, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :journals, dependent: :destroy
	has_many :boardposts, dependent: :destroy

	validates_presence_of :fname, :lname, :email
	validates_presence_of :password, on: :create
	validates_uniqueness_of :email
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardposts_helper.rb
module BoardpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Third Goal Travel</title>
	  <script src="http://maps.googleapis.com/maps/api/js"></script>
	  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
	  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
	  <meta name="viewport" content="width=device-width">
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<% if flash[:notice] %>
			<div id="flash">
				<h3><%= flash[:notice] %></h3>
			</div>
		<% end %>

		<nav>
			<ul class="left">
				<img src="/images/facebook.png">
				<img src="/images/instagram.png">
				<img src="/images/twitter.png">
			</ul>

			<% if current_user %>
				<ul class="right">
					<li><a href="/about">ABOUT</a></li>
					<div class="dropdown">
						<%= link_to "GO", countries_path, class: :dropbtn %>
							<div class="dropdown-content">
								<a href="/regions">REGIONS</a>
								<a href="/countries">COUNTRIES</a>
							</div>
					</div>
					<div class="dropdown">
						<%= link_to "MY ACCOUNT", user_path(current_user), class: :dropbtn %>
							<div class="dropdown-content" id="account-menu">
								<%= link_to "MY PROFILE", user_path(current_user) %>
								<%= link_to "EDIT ACCOUNT", edit_user_path(current_user) %>
								<%= link_to "LOG OUT", log_out_path %>
							</div>
					</div>
					
				</ul>
			<% else %>
				<ul class="right">
					<li><a href="/about">ABOUT</a></li>
					<div class="dropdown">
						<%= link_to "GO", countries_path, class: :dropbtn %>
							<div class="dropdown-content">
								<%= link_to "REGIONS", regions_path %>
								<%= link_to "COUNTRIES", countries_path %>
							</div>
					</div>
					<li><%= link_to "LOG IN", log_in_path %></li>
					<li><%= link_to "SIGN UP", sign_up_path %></li>
				</ul>
			<% end %>
			<ul class="middle">
				<% if @country %>
					<h1 id="country_name"><%= link_to @country.name, country_path(@country) %></h1>
				<% end %>
			</ul>
		</nav>

			<%= yield %>

	</body>
</html>